#!/usr/bin/env node

/**
 * Prepare CSV file from the attached data
 */

import fs from 'fs';

// The complete CSV data from the attached file
const csvData = `id,name,sku,alternate_names,category_id,short_description,description,dosage,price,is_blend,ingredients,research_applications
41b5aaf8-4d99-45af-9ba9-5605bc82d230,"2X Blend CJC-1295 Without DAC (5mg) / Ipamorelin (5mg)",YPB-BLD-001,"",6ccaa18b-fb85-43b5-a8d8-61ac7ab504f7,"Premium lyophilized 2X Blend CJC-1295 Without DAC (5mg) / Ipamorelin (5mg) for advanced blends research applications.","Premium lyophilized 2X Blend CJC-1295 Without DAC (5mg) / Ipamorelin (5mg) for advanced blends research applications. This pharmaceutical-grade compound has been specifically formulated for laboratory research purposes. Each batch undergoes rigorous quality control testing with Certificate of Analysis available upon request. Manufactured in state-of-the-art facilities following strict protocols to ensure consistency and purity. For qualified researchers and institutions only. Not for human or veterinary use.","5mg, 5mg",206.25,true,"Blend CJC-1295 Without DAC (5mg);Ipamorelin (5mg)","blends, cjc-1295 w, combination therapy, lyophilized, reconstitution required"
86444563-bee3-4686-8287-f17ec265ba33,"4X Blend GHRP-2 (5mg) / Tesamorelin (5mg) / MGF (500mcg) / Ipamorelin (2.5mg)",YPB-BLD-002,"",6ccaa18b-fb85-43b5-a8d8-61ac7ab504f7,"Premium lyophilized 4X Blend GHRP-2 (5mg) / Tesamorelin (5mg) / MGF (500mcg) / Ipamorelin (2.5mg) for advanced blends research applications.","Premium lyophilized 4X Blend GHRP-2 (5mg) / Tesamorelin (5mg) / MGF (500mcg) / Ipamorelin (2.5mg) for advanced blends research applications. This pharmaceutical-grade compound has been specifically formulated for laboratory research purposes. Each batch undergoes rigorous quality control testing with Certificate of Analysis available upon request. Manufactured in state-of-the-art facilities following strict protocols to ensure consistency and purity. For qualified researchers and institutions only. Not for human or veterinary use.","5mg, 5mg, 500mcg, 2.5mg",198.00,true,"Blend GHRP-2 (5mg);Tesamorelin (5mg);MGF (500mcg);Ipamorelin (2.5mg)","blends, ghrp-2, combination therapy, lyophilized, reconstitution required"
5f34c854-0254-4c12-a6e5-3c6e0c0b0b0b,"4X Blend Methionine (15mg) / Choline Chloride (50mg) / Carnitine (50mg) / Dexpanthenol (5mg)",YPB-BLD-003,"",6ccaa18b-fb85-43b5-a8d8-61ac7ab504f7,"Premium lyophilized 4X Blend Methionine (15mg) / Choline Chloride (50mg) / Carnitine (50mg) / Dexpanthenol (5mg) for advanced blends research applications.","Premium lyophilized 4X Blend Methionine (15mg) / Choline Chloride (50mg) / Carnitine (50mg) / Dexpanthenol (5mg) for advanced blends research applications. This pharmaceutical-grade compound has been specifically formulated for laboratory research purposes. Each batch undergoes rigorous quality control testing with Certificate of Analysis available upon request. Manufactured in state-of-the-art facilities following strict protocols to ensure consistency and purity. For qualified researchers and institutions only. Not for human or veterinary use.","15mg, 50mg, 50mg, 5mg",445.50,true,"Blend Methionine (15mg);Choline Chloride (50mg);Carnitine (50mg);Dexpanthenol (5mg)","blends, combination therapy, lyophilized, reconstitution required"
57d8f080-7200-4d33-b12a-9ef3754dd1f9,"5-Amino-1MQ (50mg)",YPB-WM-002,"",c9fd4370-fff7-4cf2-a613-b355097eebd5,"Premium lyophilized 5-Amino-1MQ (50mg) for advanced weight management research applications.","Premium lyophilized 5-Amino-1MQ (50mg) for advanced weight management research applications. This pharmaceutical-grade compound has been specifically formulated for laboratory research purposes. Each batch undergoes rigorous quality control testing with Certificate of Analysis available upon request. Manufactured in state-of-the-art facilities following strict protocols to ensure consistency and purity. For qualified researchers and institutions only. Not for human or veterinary use.","50mg",279.00,false,"","weight management, fat loss research, obesity studies, metabolic rate, body composition, lyophilized, reconstitution required"
6c87374f-48c7-4605-8f9d-b83d5ce1a8e9,"5-Amino-1MQ (50mg) x 30 Tablets",YPB-WM-003,"",c9fd4370-fff7-4cf2-a613-b355097eebd5,"Research-grade 5-Amino-1MQ (50mg) x 30 Tablets in convenient tablet form for weight management studies.","Research-grade 5-Amino-1MQ (50mg) x 30 Tablets in convenient tablet form for weight management studies. This pharmaceutical-grade compound has been specifically formulated for laboratory research purposes. Each batch undergoes rigorous quality control testing with Certificate of Analysis available upon request. Manufactured in state-of-the-art facilities following strict protocols to ensure consistency and purity. For qualified researchers and institutions only. Not for human or veterinary use.","50mg",320.85,false,"","weight management, fat loss research, obesity studies, metabolic rate, body composition, tablet form, convenient dosing"
5fe2548c-cb39-4923-b976-ded0ce173659,"5-Amino-1MQ (5mg)",YPB-WM-001,"",c9fd4370-fff7-4cf2-a613-b355097eebd5,"Premium lyophilized 5-Amino-1MQ (5mg) for advanced weight management research applications.","Premium lyophilized 5-Amino-1MQ (5mg) for advanced weight management research applications. This pharmaceutical-grade compound has been specifically formulated for laboratory research purposes. Each batch undergoes rigorous quality control testing with Certificate of Analysis available upon request. Manufactured in state-of-the-art facilities following strict protocols to ensure consistency and purity. For qualified researchers and institutions only. Not for human or veterinary use.","5mg",155.00,false,"","weight management, fat loss research, obesity studies, metabolic rate, body composition, lyophilized, reconstitution required"`;

// Write the first part, then we'll append the rest
fs.writeFileSync('./data/all_peptides_complete.csv', csvData);
console.log('✅ CSV file started. Run append-csv.js to complete it.');
