# Render deployment configuration
services:
  - type: web
    name: shrine-repo-dojo
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://shrine_db_yzkh_user:18DobeaCbpF9ZX3jAXnaz3WIdrTXeINS@dpg-d3ceokj7mgec73aefelg-a.oregon-postgres.render.com/shrine_db_yzkh?sslmode=require
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /api/health
    plan: starter
    # Custom domain configuration
    customDomains:
      - peptidedojo.com
      - www.peptidedojo.com