# Render deployment configuration
services:
  - type: web
    name: shrine-repo-dojo
    runtime: node
    buildCommand: npm install &&极 npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /api/health
    plan: starter