services:
  - type: web
    name: shrine-repo-dojo
    runtime: node
    buildCommand: npm install
    startCommand: node simple-server.js
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /api/health
    plan: starter
